const sourceList = {
	'ABC News': 'abcnews.com',
	'Associated Press': 'apnews.com',
	'Axios': 'axios.com',
	'BBC News': 'bbc.com',
	'Bloomberg': 'bloomberg.com',
	'Breitbart News': 'breitbart.com',
	'Business Insider': 'businessinsider.com',
	'Buzzfeed': 'buzzfeed.com',
	'CBS News': 'cbsnews.com',
	'CNBC': 'cnbc.com',
	'CNN': 'cnn.com',
	'CNET': 'cnet.com',
	'Financial Post': 'financialpost.com',
	'Forbes': 'forbes.com',
	'Fortune': 'fortune.com',
	'Fox News': 'foxnews.com',
	'Free Think': 'freethink.com',
	'MSNBC': 'msnbc.com',
	'NBC News': 'nbcnews.com',
	'NPR': 'npr.org',
	'National Review': 'nationalreview.com',
	'New York Magazine': 'nymag.com',
	'New York Post': 'nypost.com',
	'Politico': 'politico.com',
	'Quillette': 'quillette.com',
	'Reason': 'reason.com',
	'Reuters': 'reuters.com',
	'Tech Crunch': 'techcrunch.com',
	'The Economist': 'economist.com',
	'The Hill': 'thehill.com',
	'The Independent': 'independent.co.uk',
	'The Intercept': 'theintercept.com',
	'The New York Times': 'nytimes.com',
	'The Next Web': 'thenextweb.com',
	'The Spectator World': 'spectatorworld.com',
	'The Verge': 'theverge.com',
	'The Wall Street Journal': 'wsj.com',
	'The Washington Post': 'washingtonpost.com',
	'Time': 'time.com',
	'USA Today': 'usatoday.com',
	'UnHerd': 'unherd.com',
	'Vice': 'vice.com',
	'Wired': 'wired.com'
}

export { sourceList }