const sourceList = {
	'ABC News': 'abcnews.com',
	'Al Jazeera': 'aljazeera.com',
	'Associated Press': 'apnews.com',
	'Axios': 'axios.com',
	'BBC News': 'bbc.com',
	'Bloomberg': 'bloomberg.com',
	'Breitbart News': 'breitbart.com',
	'Business Insider': 'businessinsider.com',
	'Buzzfeed': 'buzzfeed.com',
	'CBS News': 'cbsnews.com',
	'CNBC': 'cnbc.com',
	'CNN': 'cnn.com',
	'CNET': 'cnet.com',
	'Financial Post': 'financialpost.com',
	'Forbes': 'forbes.com',
	'Foreign Policy': 'foreignpolicy.com',
	'Fortune': 'fortune.com',
	'Fox Business': 'foxbusiness.com',
	'Fox News': 'foxnews.com',
	'Gallup': 'gallup.com',
	// 'Free Think': 'freethink.com',
	'Los Angeles Times': 'latimes.com',
	'Market Watch': 'marketwatch.com',
	'Mother Jones': 'motherjones.com',
	'MSNBC': 'msnbc.com',
	'NBC News': 'nbcnews.com',
	'NPR': 'npr.org',
	'National Review': 'nationalreview.com',
	'New York Magazine': 'nymag.com',
	'New York Post': 'nypost.com',
	'PBS': 'pbs.org',
	'Pew Research Center': 'pewresearch.org',
	'Politico': 'politico.com',
	// 'Quillette': 'quillette.com',
	'Reason': 'reason.com',
	'Reuters': 'reuters.com',
	'Tech Crunch': 'techcrunch.com',
	'The Atlantic': 'theatlantic.com',
	'The Economist': 'economist.com',
	'The Guardian': 'theguardian.com',
	'The Hill': 'thehill.com',
	'The Intercept': 'theintercept.com',
	'The New Yorker': 'newyorker.com',
	'The New York Times': 'nytimes.com',
	'The Verge': 'theverge.com',
	'The Wall Street Journal': 'wsj.com',
	'The Washington Post': 'washingtonpost.com',
	'Time': 'time.com',
	'USA Today': 'usatoday.com',
	// 'UnHerd': 'unherd.com',
	'Vice': 'vice.com',
	'Vox': 'vox.com',
	'Wired': 'wired.com',
	'Yahoo News': 'yahoo.com'
}

export { sourceList }